### ISSUE TITLE
ValueError: can't optimize a non-leaf Tensor

### ISSUE THREAD

**Issue by joaogui1** [kevinzakka/nca#5]
When I try to use the nca part of the dim_reduct example I get `ValueError: can't optimize a non-leaf Tensor`, any idea what could be wrong?

**Comment by kevinzakka** [comment]
Hey @joaogui1, can you post a minimal reproducible example? Also what PyTorch version are you using?

**Comment by joaogui1** [comment]
As I said I am running one of the codes in examples, specifically the one on dimensionality reduction
```
from torchnca import NCA
import torch
import numpy as onp
def make_circle(r, num_samples):
  t = onp.linspace(0, 2*np.pi, num_samples)
  xc, yc = 0, 0  # circle center coordinates
  x = r*onp.cos(t) + 0.2*onp.random.randn(num_samples) + xc
  y = r*onp.sin(t) + 0.2*onp.random.randn(num_samples) + yc
  return x, y


def gen_data(num_samples, num_classes, mean, std):
 num_samples_per = num_samples // num_classes
  X = []
  y = []
  for i, r in enumerate(range(num_classes)):
    # first two dimensions are that of a circle
    x1, x2 = make_circle(r+1.5, num_samples_per)
    # third dimension is Gaussian noise
    x3 = std*onp.random.randn(num_samples_per) + mean
    X.append(onp.stack([x1, x2, x3]))
    y.append(onp.repeat(i, num_samples_per))
  X = onp.concatenate(X, axis=1)
  y = onp.concatenate(y)
  indices = list(range(X.shape[1]))
  onp.random.shuffle(indices)
  X = X[:, indices]
  y = y[indices]
  X = X.T  # make it (N, D)
  return X, y

onp.random.seed(1)
num_samples = 500
X, y = gen_data(num_samples, 5, 0, 0.5)

torch.cuda.manual_seed(1)
device = torch.device("cuda")
X = torch.from_numpy(X).float().to(device)
y = torch.from_numpy(y).long().to(device)
nca = NCA(dim=2, init='identity', max_iters=1000, tol=1e-5)
nca.train(X, y, batch_size=None, weight_decay=20)
X_nca = nca(X).detach().cpu().numpy()
```
pytorch version is 1.4.0

**Comment by joaogui1** [comment]
I can trade the whole data generating process to get a minimal example:
```
onp.random.seed(1)
num_samples = 500
X, y = onp.random.randn(num_samples, 5), onp.random.randn(num_samples, 5)
torch.cuda.manual_seed(1)
device = torch.device("cuda")
X = torch.from_numpy(X).float().to(device)
y = torch.from_numpy(y).long().to(device)
nca = NCA(dim=2, init='identity', max_iters=1000, tol=1e-5)
nca.train(X, y, batch_size=None, weight_decay=20)
X_nca = nca(X).detach().cpu().numpy()
```
This already generates the error in colab

**Comment by kevinzakka** [comment]
Hey @joaogui1, should be fixed in the newest commit thanks to @brentyi ! Cheers

**Comment by lidh15** [comment]
have you really release the new version? I install via pip and the problem is still there.
![image](https://user-images.githubusercontent.com/14806954/75931706-83913800-5e6d-11ea-8907-ae389995d77d.png)

**Comment by kevinzakka** [comment]
@lidh15 forgot to push it to pypi, should be available shortly. Do let me know if it works out!
